[package]
name = "kobo-sim-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
kobo-errors = { path = "../kobo-errors" }
kobo-ir = { path = "../kobo-ir" }
kobo-parser = { path = "../kobo-parser" }
proc-macro2 = { workspace = true }
syn = { workspace = true }
