use crate::{KErrorCode, Severity};

use super::{
    entry, DiagnosticCategory, DiagnosticRegistryEntry, MachineEditPolicy, ModeBehavior,
    SeverityPolicy, SuggestionPolicy,
};
pub(super) fn entries() -> Vec<DiagnosticRegistryEntry> {
    use DiagnosticCategory::{BoundaryPolicy, Liveness, Nondeterminism, Replay, Simulation};
    use MachineEditPolicy::{NotApplicable, RefuseByDefault};
    use ModeBehavior::{NoModeDependency, ReplayBoundaryPrompt, ScriptDebtStrictError};
    use Severity::{Error, Warning};
    use SeverityPolicy::{Always, ScriptDebtCheckedWarningStrictError};
    use SuggestionPolicy::{BoundaryPolicy as BoundarySuggestion, HelpOnly, ReviewOnly};

    vec![
        entry(
            KErrorCode::K0100,
            "checked-runtime-liveness-token-dropped",
            "checked scenario dropped an unresolved liveness token",
            "A checked-profile scenario dropped a runtime liveness token before ack, nack, requeue, commit, rollback, or another required action.",
            "Checked simulation records liveness obligations at runtime. A token cannot disappear without one of its required actions or an explicit debt record.",
            Liveness,
            Warning,
            ScriptDebtCheckedWarningStrictError,
            ScriptDebtStrictError,
            ReviewOnly,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0101,
            "liveness-obligation-escaped",
            "liveness obligation escapes local analysis",
            "A must_call value escapes through a return, task, store, or external call where local analysis cannot prove the required action happens.",
            "Kobo keeps this as reviewable debt because the obligation may be handled elsewhere, but the local function no longer proves it.",
            Liveness,
            Warning,
            ScriptDebtCheckedWarningStrictError,
            ScriptDebtStrictError,
            ReviewOnly,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0102,
            "raw-nondeterminism-on-replay-path",
            "raw nondeterminism appears on a replay path",
            "A replay-critical path uses raw nondeterminism such as time, random, spawn, filesystem, network, process, or external I/O.",
            "Exact replay needs the same event stream each time. Raw nondeterminism must be modeled, recorded, or acknowledged as replay debt.",
            Nondeterminism,
            Warning,
            Always(Warning),
            ScriptDebtStrictError,
            ReviewOnly,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0103,
            "uncontrolled-effect-blocks-replay",
            "scenario cannot replay an uncontrolled effect",
            "A scenario reached an uncontrolled effect that was neither modeled nor recorded, so Kobo cannot replay the failure exactly.",
            "Add a deterministic model, record the effect stream, choose a boundary policy, or mark this scenario as partial replay debt.",
            Replay,
            Error,
            Always(Error),
            ReplayBoundaryPrompt,
            BoundarySuggestion,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0104,
            "kwit-replay-diverged",
            ".kwit replay diverged from recorded history",
            "Replay observed an event stream that diverged from the history recorded in the .kwit witness.",
            "Compare the expected and observed events, verify source identity, and regenerate the witness after intentional source or boundary changes.",
            Replay,
            Error,
            Always(Error),
            NoModeDependency,
            ReviewOnly,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0105,
            "sim-quick-budget-exceeded",
            "scenario exceeded quick-profile budget",
            "A deterministic quick-profile scenario exceeded its configured tick or event budget.",
            "Increase the simulation profile budget, reduce the scenario, or run a deeper profile when the longer exploration is intentional.",
            Simulation,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0114,
            "malformed-must-call-attribute",
            "malformed must_call attribute",
            "A must_call obligation attribute could not be parsed into one or more named actions.",
            "Use `#[kobo::must_call(commit | rollback)]` with action names separated by a single `|`.",
            Liveness,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0115,
            "invalid-kwit-witness-schema",
            "invalid kwit witness schema",
            "A .kwit witness is missing required metadata or uses an unsupported schema version.",
            "Legacy schema_version 0 witnesses validate metadata only; exact replay requires schema_version 1 event history and uses K0104 for divergence.",
            BoundaryPolicy,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0116,
            "scenario-coverage-incomplete",
            "scenario coverage incomplete",
            "A scenario used syntax or runtime behavior that Kobo has not modeled for exact replay yet.",
            "Exact replay is allowed only when compiler semantics and generated harness execution cover the full modeled island. Unsupported constructs must downgrade the witness to partial coverage.",
            Replay,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0117,
            "semantic-harness-trace-diverged",
            "semantic trace and harness trace diverged",
            "The compiler semantic trace and generated harness trace did not agree.",
            "Full-depth replay requires independent semantic and harness evidence. A mismatch means Kobo cannot trust the witness as exact evidence.",
            Replay,
            Error,
            Always(Error),
            NoModeDependency,
            ReviewOnly,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0118,
            "stale-evidence-artifact",
            "stale or mismatched evidence artifact",
            "An editor or replay action points at a witness or session artifact that does not match the current source and target.",
            "Artifact-backed actions must verify source hash, target, and digest before offering replay, perf, or audit evidence.",
            Replay,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0106,
            "witness-shrink-unsafe",
            "witness shrink is unsafe",
            "A requested witness shrink would remove replay evidence needed to preserve deterministic or boundary obligations.",
            "Keep the witness evidence or regenerate a smaller witness through a checked shrink pass that preserves required replay and boundary facts.",
            BoundaryPolicy,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0109,
            "invalid-field-capability-view",
            "invalid field capability view",
            "A using field capability list names duplicate or unavailable fields.",
            "Kobo validates field capability views before lowering so a `using { ... }` list cannot silently claim access to a field that does not exist.",
            BoundaryPolicy,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0107,
            "unmodeled-external-boundary",
            "unmodeled external crate boundary",
            "An external crate boundary is usable for normal Rust compatibility but blocks exact replay until a boundary policy is chosen.",
            "normal Rust crates remain allowed in Kobo. Exact replay cannot cross this boundary until you choose one policy: model, record, outside, opaque, or debt.",
            BoundaryPolicy,
            Warning,
            Always(Warning),
            ReplayBoundaryPrompt,
            BoundarySuggestion,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0108,
            "replay-obligation-suppressed",
            "replay obligation suppressed",
            "A replay, liveness, or boundary obligation was suppressed with a recorded reason.",
            "Kobo keeps reason-bearing suppression as reviewable evidence instead of pretending the boundary or obligation was modeled.",
            BoundaryPolicy,
            Warning,
            Always(Warning),
            ReplayBoundaryPrompt,
            BoundarySuggestion,
            RefuseByDefault,
        ),
    ]
}
