use crate::{KErrorCode, Severity};

use super::{
    entry, DiagnosticCategory, DiagnosticRegistryEntry, MachineEditPolicy, ModeBehavior,
    SeverityPolicy, SuggestionPolicy,
};
pub(super) fn entries() -> Vec<DiagnosticRegistryEntry> {
    use DiagnosticCategory::{BoundaryPolicy, Liveness, Nondeterminism, Replay, Simulation};
    use MachineEditPolicy::{NotApplicable, RefuseByDefault};
    use ModeBehavior::{NoModeDependency, ReplayBoundaryPrompt, ScriptDebtStrictError};
    use Severity::{Error, Warning};
    use SeverityPolicy::{Always, ScriptDebtCheckedWarningStrictError};
    use SuggestionPolicy::{BoundaryPolicy as BoundarySuggestion, HelpOnly, ReviewOnly};

    vec![
        entry(
            KErrorCode::K0100,
            "obligation-not-finished",
            "I expected this obligation to finish",
            "A scenario path leaves the delivery open.",
            "Every path through this scenario must end the obligation or pass it on as debt.",
            Liveness,
            Warning,
            ScriptDebtCheckedWarningStrictError,
            ScriptDebtStrictError,
            ReviewOnly,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0101,
            "obligation-leaves-local-check",
            "an obligation leaves the code I can check",
            "An obligation is leaving through a return, task, store, or external call.",
            "I keep this as reviewable debt because cleanup may happen elsewhere, but this source path no longer proves it.",
            Liveness,
            Warning,
            ScriptDebtCheckedWarningStrictError,
            ScriptDebtStrictError,
            ReviewOnly,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0102,
            "replay-path-can-change",
            "this replay path can change between runs",
            "Time, randomness, scheduling, filesystem, network, process, or outside I/O appears on a replay path.",
            "Exact replay needs the same event stream each time, so values that can change must be modeled, recorded, or accepted as debt.",
            Nondeterminism,
            Warning,
            Always(Warning),
            ScriptDebtStrictError,
            ReviewOnly,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0103,
            "action-not-replayable-yet",
            "I do not know how to replay this action yet",
            "This action can affect the outside world, but the scenario does not model or record it.",
            "To replay this failure later, I need the action to be modeled, recorded, moved outside replay, or accepted as debt.",
            Replay,
            Error,
            Always(Error),
            ReplayBoundaryPrompt,
            BoundarySuggestion,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0104,
            "kwit-replay-diverged",
            "replay witness diverged from recorded history",
            "Replay observed an event stream that diverged from the history recorded in the witness.",
            "Compare the expected and observed events, verify source identity, and regenerate the witness after intentional source or boundary changes.",
            Replay,
            Error,
            Always(Error),
            NoModeDependency,
            ReviewOnly,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0105,
            "sim-quick-budget-exceeded",
            "scenario exceeded quick-profile budget",
            "A deterministic quick-profile scenario exceeded its configured tick or event budget.",
            "Increase the simulation profile budget, reduce the scenario, or run a deeper profile when the longer exploration is intentional.",
            Simulation,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0114,
            "malformed-must-call-attribute",
            "malformed must_call attribute",
            "A must_call obligation attribute could not be parsed into one or more named actions.",
            "Use `#[kobo::must_call(commit | rollback)]` with action names separated by a single `|`.",
            Liveness,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0115,
            "invalid-kwit-witness-schema",
            "invalid kwit witness schema",
            "A .kwit witness is missing required metadata or uses an unsupported schema version.",
            "Older witnesses validate metadata only; exact replay requires event history and uses K0104 for divergence.",
            BoundaryPolicy,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0116,
            "scenario-coverage-incomplete",
            "scenario coverage incomplete",
            "A scenario used syntax or runtime behavior that Kobo has not modeled for exact replay yet.",
            "Exact replay is allowed only when Kobo can model the whole scenario and generated harness run. Uncovered behavior downgrades the witness to partial coverage.",
            Replay,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0117,
            "semantic-harness-trace-diverged",
            "semantic trace and harness trace diverged",
            "The compiler semantic trace and generated harness trace did not agree.",
            "Full-depth replay requires independent semantic and harness evidence. A mismatch means Kobo cannot trust the witness as exact evidence.",
            Replay,
            Error,
            Always(Error),
            NoModeDependency,
            ReviewOnly,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0118,
            "stale-evidence-artifact",
            "stale or mismatched evidence artifact",
            "An editor or replay action points at a witness or session artifact that does not match the current source and target.",
            "Artifact-backed actions must verify source hash, target, and digest before offering replay, perf, or audit evidence.",
            Replay,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0106,
            "witness-shrink-unsafe",
            "witness shrink is unsafe",
            "A requested witness shrink would remove replay evidence needed to preserve deterministic or boundary obligations.",
            "Keep the witness evidence or regenerate a smaller witness through a checked shrink pass that preserves required replay and boundary facts.",
            BoundaryPolicy,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0109,
            "invalid-field-capability-view",
            "invalid field capability view",
            "A using field capability list names duplicate or unavailable fields.",
            "Kobo validates field capability views before lowering so a `using { ... }` list cannot silently claim access to a field that does not exist.",
            BoundaryPolicy,
            Error,
            Always(Error),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0107,
            "unmodeled-external-boundary",
            "unmodeled external crate boundary",
            "An external crate boundary is usable for normal Rust compatibility but blocks exact replay until a boundary policy is chosen.",
            "normal Rust crates remain allowed in Kobo. Exact replay cannot cross this boundary until you choose one policy: model, record, outside, opaque, or debt.",
            BoundaryPolicy,
            Warning,
            Always(Warning),
            ReplayBoundaryPrompt,
            BoundarySuggestion,
            RefuseByDefault,
        ),
        entry(
            KErrorCode::K0108,
            "replay-obligation-suppressed",
            "replay obligation suppressed",
            "A replay, liveness, or boundary obligation was suppressed with a recorded reason.",
            "Kobo keeps reason-bearing suppression as reviewable evidence instead of pretending the boundary or obligation was modeled.",
            BoundaryPolicy,
            Warning,
            Always(Warning),
            ReplayBoundaryPrompt,
            BoundarySuggestion,
            RefuseByDefault,
        ),
    ]
}
