use crate::{KErrorCode, Severity};

use super::{
    entry, DiagnosticCategory, DiagnosticRegistryEntry, MachineEditPolicy, ModeBehavior,
    SeverityPolicy, SuggestionPolicy,
};
pub(super) fn entries() -> Vec<DiagnosticRegistryEntry> {
    use DiagnosticCategory::Solver;
    use MachineEditPolicy::NotApplicable;
    use ModeBehavior::NoModeDependency;
    use Severity::{Error, Note, Warning};
    use SeverityPolicy::Always;
    use SuggestionPolicy::{HelpOnly, ReviewOnly};

    vec![
        entry(
            KErrorCode::K0080,
            "structural-ownership-conflict",
            "structural ownership conflict - no automatic fix possible",
            "Kobo found an ownership shape that needs a human design choice.",
            "More than one architecture could be correct, or the current shape needs a design boundary. Kobo reports the conflict instead of fabricating a silent rewrite.",
            Solver,
            Note,
            Always(Note),
            NoModeDependency,
            ReviewOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0080P1,
            "migration-architecture-decision",
            "ownership pattern will require architectural decision at migration",
            "A precursor ownership pattern is likely to need human migration design.",
            "Kobo reports this as advisory debt so it can be handled before stricter migration gates.",
            Solver,
            Note,
            Always(Note),
            NoModeDependency,
            ReviewOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0080P2,
            "rc-back-pointer-cycle-risk",
            "parent-child Rc back-pointer tree - cycle risk",
            "Parent and child links can create an Rc cycle.",
            "Use Weak links or a different ownership shape when migrating this structure.",
            Solver,
            Note,
            Always(Note),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0080P3,
            "shared-mutable-callsite-hotspot",
            "shared mutable state at 3+ call sites",
            "A value is mutated through several call sites and may need a design decision.",
            "Kobo tracks this as migration debt because automatic wrapping may hide an architectural choice.",
            Solver,
            Note,
            Always(Note),
            NoModeDependency,
            ReviewOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0080P4,
            "self-referential-struct",
            "self-referential struct - infinite size without indirection",
            "A structure refers to itself without an indirection boundary.",
            "Kobo reports this early because Rust requires an indirection such as Box, Rc, or a redesigned structure.",
            Solver,
            Note,
            Always(Note),
            NoModeDependency,
            HelpOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0081,
            "ownership-cluster-too-large",
            "ownership problem is too large to choose automatically",
            "Too many ownership choices are connected in one part of the code.",
            "Kobo stops instead of making a silent partial decision. Split the code or add a local ownership annotation so the intended owner is clear.",
            Solver,
            Error,
            Always(Error),
            NoModeDependency,
            ReviewOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0082,
            "ownership-budget-exceeded",
            "ownership analysis took too long",
            "Kobo ran out of budget before reaching a complete answer.",
            "Budget exhaustion is distinct from no-solution so users can decide whether to increase budget or simplify the code.",
            Solver,
            Error,
            Always(Error),
            NoModeDependency,
            ReviewOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0083,
            "ownership-choice-needs-review",
            "ownership choice requires human review",
            "Kobo found more than one valid ownership candidate.",
            "Kobo may choose a lowest-risk candidate for codegen, but review output must expose the alternatives.",
            Solver,
            Warning,
            Always(Warning),
            NoModeDependency,
            ReviewOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0084,
            "ownership-medium-confidence",
            "ownership choice needs confirmation",
            "Kobo found an ownership choice that is plausible but not strong enough to hide from review.",
            "Kobo reports medium-confidence choices so migration remains auditable.",
            Solver,
            Warning,
            Always(Warning),
            NoModeDependency,
            ReviewOnly,
            NotApplicable,
        ),
        entry(
            KErrorCode::K0085,
            "ownership-low-confidence",
            "ownership suggestion needs manual review",
            "A low-confidence ownership choice requires human review.",
            "Kobo keeps low-confidence picks visible rather than treating them as final migration decisions.",
            Solver,
            Warning,
            Always(Warning),
            NoModeDependency,
            ReviewOnly,
            NotApplicable,
        ),
    ]
}
