[package]
name    = "kobo-transform"
version = "0.1.0"
edition = "2021"

[dependencies]
kobo-ir     = { path = "../kobo-ir" }
kobo-parser = { path = "../kobo-parser" }
proc-macro2 = { workspace = true }
quote       = { workspace = true }
syn         = { workspace = true }

[dev-dependencies]
kobo-codegen = { path = "../kobo-codegen" }
toml = { workspace = true }
