use std::collections::BTreeMap;

use crate::{KErrorCode, Severity};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DiagnosticRegistry {
    entries: BTreeMap<&'static str, DiagnosticRegistryEntry>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DiagnosticRegistryEntry {
    pub code: KErrorCode,
    pub code_text: &'static str,
    pub title: &'static str,
    pub summary: &'static str,
    pub explain: &'static str,
    pub category: DiagnosticCategory,
    pub status: DiagnosticStatus,
    pub default_severity: Severity,
    pub severity_policy: SeverityPolicy,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum DiagnosticCategory {
    Ownership,
    Performance,
    StrictBoundary,
    Async,
    Solver,
    Parser,
    RustcRemap,
    MigrationBoundary,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum DiagnosticStatus {
    Active,
    Reserved,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum SeverityPolicy {
    Always(Severity),
    OwnershipModeDependent,
    AsyncModeDependent,
    HiddenUntilActive,
}

impl SeverityPolicy {
    pub const fn resolve(self, mode: kobo_ir::KoboMode) -> Option<Severity> {
        match self {
            Self::Always(severity) => Some(severity),
            Self::OwnershipModeDependent => match mode {
                kobo_ir::KoboMode::Script => None,
                kobo_ir::KoboMode::Checked => Some(Severity::Warning),
                kobo_ir::KoboMode::Strict => Some(Severity::Error),
            },
            Self::AsyncModeDependent => match mode {
                kobo_ir::KoboMode::Script | kobo_ir::KoboMode::Checked => Some(Severity::Warning),
                kobo_ir::KoboMode::Strict => Some(Severity::Error),
            },
            Self::HiddenUntilActive => None,
        }
    }
}

impl DiagnosticRegistry {
    pub fn get(&self, code: KErrorCode) -> Option<&DiagnosticRegistryEntry> {
        self.find_by_code_text(code.as_str())
    }

    pub fn find_by_code_text(&self, code_text: &str) -> Option<&DiagnosticRegistryEntry> {
        self.entries.get(code_text)
    }
}

pub fn diagnostic_registry() -> DiagnosticRegistry {
    let mut entries = BTreeMap::new();
    for entry in registry_entries() {
        entries.insert(entry.code_text, entry);
    }
    DiagnosticRegistry { entries }
}

fn registry_entries() -> Vec<DiagnosticRegistryEntry> {
    use DiagnosticCategory::*;
    use DiagnosticStatus::Active;
    use Severity::*;
    use SeverityPolicy::*;

    vec![
        DiagnosticRegistryEntry {
            code: KErrorCode::K0001,
            code_text: "K0001",
            title: "value used after move",
            summary: "A value is used after ownership has moved away from it.",
            explain: "Kobo tracks ownership facts before lowering to Rust. This diagnostic points at the use that would require a value after it has moved.",
            category: Ownership,
            status: Active,
            default_severity: Warning,
            severity_policy: OwnershipModeDependent,
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0002,
            code_text: "K0002",
            title: "cannot borrow as mutable - already borrowed",
            summary: "A mutable borrow conflicts with an existing borrow.",
            explain: "Kobo found borrow facts that cannot both be satisfied without changing ownership shape or shortening one borrow.",
            category: Ownership,
            status: Active,
            default_severity: Warning,
            severity_policy: OwnershipModeDependent,
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0019,
            code_text: "K0019",
            title: "ownership diagnostic",
            summary: "An ownership condition needs a stronger mode-dependent guarantee.",
            explain: "K0019 is the compatibility bucket for ownership diagnostics that have not yet been assigned a narrower code.",
            category: Ownership,
            status: Active,
            default_severity: Warning,
            severity_policy: OwnershipModeDependent,
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0020,
            code_text: "K0020",
            title: "RefCell accessed >10,000 times in hot path",
            summary: "A diagnostic owner recorded many dynamic borrow checks in a hot path.",
            explain: "Kobo records runtime borrow counters so migration work can prioritize expensive shared-mutable paths.",
            category: Performance,
            status: Active,
            default_severity: Warning,
            severity_policy: Always(Warning),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0021,
            code_text: "K0021",
            title: "DiagOwner borrow counter saturated - count understated",
            summary: "A diagnostic owner counter reached its maximum value.",
            explain: "The program continued, but the reported count is a lower bound because the counter saturated.",
            category: Performance,
            status: Active,
            default_severity: Warning,
            severity_policy: Always(Warning),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0025,
            code_text: "K0025",
            title: "soft hint ignored - constraint conflict",
            summary: "A Kobo hint could not be applied because it conflicts with required ownership facts.",
            explain: "Hints are advisory. Kobo refuses or reports a hint when applying it would violate the current facts.",
            category: StrictBoundary,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0026,
            code_text: "K0026",
            title: "relax attribute has no effect or is malformed",
            summary: "A relax attribute is ineffective or invalid for the current context.",
            explain: "Kobo reports relax misuse so mode boundaries stay explicit and reviewable.",
            category: Performance,
            status: Active,
            default_severity: Warning,
            severity_policy: Always(Warning),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0030,
            code_text: "K0030",
            title: "resource handle moved - cannot alias file handle",
            summary: "A resource handle cannot be safely aliased through ownership wrapping.",
            explain: "Kobo keeps resource ownership explicit because duplicating or aliasing OS-backed handles can change behavior.",
            category: StrictBoundary,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0031,
            code_text: "K0031",
            title: "engine-owned binding capped to PlainOwned",
            summary: "A framework-managed engine binding was prevented from escalating to shared ownership.",
            explain: "Engine-managed state must stay owned by the framework unless the source explicitly opts into a supported escape path.",
            category: Performance,
            status: Active,
            default_severity: Warning,
            severity_policy: Always(Warning),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0032,
            code_text: "K0032",
            title: "live borrow at move forces shared ownership",
            summary: "A borrow remains live when a value moves.",
            explain: "Kobo uses KIR liveness to keep this move from invalidating a later borrow use.",
            category: Performance,
            status: Active,
            default_severity: Warning,
            severity_policy: Always(Warning),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0041,
            code_text: "K0041",
            title: "cannot enter @strict block - value has active aliases",
            summary: "An @strict block would start while aliases are still active.",
            explain: "Strict regions need zero-cost ownership guarantees at the boundary, so active aliases must end before entry.",
            category: StrictBoundary,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0042,
            code_text: "K0042",
            title: "closure captures LocalOwned<T> across @strict boundary",
            summary: "A closure carries a wrapped local value across a strict boundary.",
            explain: "Kobo rejects this because strict boundary guards cannot be safely represented inside the closure capture.",
            category: StrictBoundary,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0043,
            code_text: "K0043",
            title: "value moved inside @strict block - cannot re-wrap on exit",
            summary: "A value moved inside a strict block cannot be restored to its wrapper on exit.",
            explain: "Kobo keeps strict boundary exit behavior explicit so generated ownership state remains coherent.",
            category: StrictBoundary,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0044,
            code_text: "K0044",
            title: "labeled break or continue crosses @strict boundary",
            summary: "A labeled control-flow jump would exit an @strict region unsafely.",
            explain: "Kobo rejects labeled jumps that bypass strict-region guard teardown.",
            category: StrictBoundary,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0060,
            code_text: "K0060",
            title: "RefCell borrow is live at suspend point",
            summary: "A non-Send borrow would remain live across async suspension.",
            explain: "Kobo reports async ownership hazards before lowering code that would fail executor requirements.",
            category: Async,
            status: Active,
            default_severity: Warning,
            severity_policy: AsyncModeDependent,
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0061,
            code_text: "K0061",
            title: "future requires Send but value cannot safely cross thread boundary",
            summary: "An async future requires Send but a captured value cannot satisfy that boundary.",
            explain: "Kobo refuses silent Arc<Mutex<T>> insertion. Use an explicit async sharing annotation or restructure the task boundary.",
            category: Async,
            status: Active,
            default_severity: Warning,
            severity_policy: AsyncModeDependent,
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0062,
            code_text: "K0062",
            title: "Mutex guard would live across .await",
            summary: "A lock guard would cross an async suspension point.",
            explain: "Holding locks across await can deadlock or make futures non-Send; drop the guard before the await.",
            category: Async,
            status: Active,
            default_severity: Warning,
            severity_policy: AsyncModeDependent,
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0063,
            code_text: "K0063",
            title: "@strict block inside async fn without @strict async fn",
            summary: "A strict block appears in an async function without the async-aware strict contract.",
            explain: "Kobo needs explicit async strict semantics before it can preserve zero-cost guarantees across await boundaries.",
            category: Async,
            status: Active,
            default_severity: Warning,
            severity_policy: AsyncModeDependent,
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0064,
            code_text: "K0064",
            title: "@strict inside async block - ownership cannot be tracked across yield",
            summary: "A guard-like value is live across an await point.",
            explain: "Kobo reports guard liveness because it can produce deadlocks or non-Send futures.",
            category: Async,
            status: Active,
            default_severity: Warning,
            severity_policy: AsyncModeDependent,
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0065,
            code_text: "K0065",
            title: "select branch may not be cancel-safe",
            summary: "A select branch contains an operation that may lose progress if cancelled.",
            explain: "Kobo flags non-cancel-safe operations so async control flow stays reviewable before stronger simulation checks arrive.",
            category: Async,
            status: Active,
            default_severity: Warning,
            severity_policy: AsyncModeDependent,
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0067,
            code_text: "K0067",
            title: "handler request-state leaks across async boundary",
            summary: "A handler-local request value is captured by a longer-lived async task.",
            explain: "Request state should not outlive its request unless it is cloned, modeled, or moved into an explicit actor.",
            category: Async,
            status: Active,
            default_severity: Warning,
            severity_policy: AsyncModeDependent,
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0080,
            code_text: "K0080",
            title: "structural ownership conflict - no automatic fix possible",
            summary: "The solver found an ownership structure that requires human design input.",
            explain: "Kobo reports structural ownership conflicts as debt or review prompts rather than fabricating a silent rewrite.",
            category: Solver,
            status: Active,
            default_severity: Note,
            severity_policy: Always(Note),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0080P1,
            code_text: "K0080-P1",
            title: "ownership pattern will require architectural decision at migration",
            summary: "A precursor ownership pattern is likely to need human migration design.",
            explain: "Kobo reports this as advisory debt so it can be handled before stricter migration gates.",
            category: Solver,
            status: Active,
            default_severity: Note,
            severity_policy: Always(Note),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0080P2,
            code_text: "K0080-P2",
            title: "parent-child Rc back-pointer tree - cycle risk",
            summary: "Parent and child links can create an Rc cycle.",
            explain: "Use Weak links or a different ownership shape when migrating this structure.",
            category: Solver,
            status: Active,
            default_severity: Note,
            severity_policy: Always(Note),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0080P3,
            code_text: "K0080-P3",
            title: "shared mutable state at 3+ call sites",
            summary: "A value is mutated through several call sites and may need a design decision.",
            explain: "Kobo tracks this as migration debt because automatic wrapping may hide an architectural choice.",
            category: Solver,
            status: Active,
            default_severity: Note,
            severity_policy: Always(Note),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0080P4,
            code_text: "K0080-P4",
            title: "self-referential struct - infinite size without indirection",
            summary: "A structure refers to itself without an indirection boundary.",
            explain: "Kobo reports this early because Rust requires an indirection such as Box, Rc, or a redesigned structure.",
            category: Solver,
            status: Active,
            default_severity: Note,
            severity_policy: Always(Note),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0081,
            code_text: "K0081",
            title: "ownership cluster too large for automatic solving",
            summary: "A constraint cluster exceeds the configured automatic solver limit.",
            explain: "Kobo stops instead of making a silent partial decision when the solver input is too large.",
            category: Solver,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0082,
            code_text: "K0082",
            title: "solver exceeded its time budget",
            summary: "The solver ran out of budget before reaching a complete answer.",
            explain: "Budget exhaustion is distinct from no-solution so users can decide whether to increase budget or simplify the code.",
            category: Solver,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0083,
            code_text: "K0083",
            title: "solver decision requires human review",
            summary: "The solver found more than one valid ownership candidate.",
            explain: "Kobo may choose a lowest-risk candidate for codegen, but review output must expose the alternatives.",
            category: Solver,
            status: Active,
            default_severity: Warning,
            severity_policy: Always(Warning),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0084,
            code_text: "K0084",
            title: "solver made a provisional decision with medium confidence",
            summary: "A solver choice is acceptable but not strong enough to hide from review.",
            explain: "Kobo reports medium-confidence choices so migration remains auditable.",
            category: Solver,
            status: Active,
            default_severity: Warning,
            severity_policy: Always(Warning),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0085,
            code_text: "K0085",
            title: "solver applied a low-confidence heuristic - verify manually",
            summary: "A low-confidence ownership choice requires human review.",
            explain: "Kobo keeps low-confidence picks visible rather than treating them as final migration decisions.",
            category: Solver,
            status: Active,
            default_severity: Warning,
            severity_policy: Always(Warning),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0090,
            code_text: "K0090",
            title: "migration cannot continue - value crosses into external crate",
            summary: "Ownership depends on a boundary Kobo cannot currently solve.",
            explain: "External crate boundaries require an explicit ownership hint, summary, or deferral instead of silent inference.",
            category: MigrationBoundary,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0095,
            code_text: "K0095",
            title: "ownership of macro-generated value cannot be inferred",
            summary: "A macro-generated value lacks enough source structure for ownership inference.",
            explain: "Kobo reports macro boundaries explicitly because generated ownership facts may not map cleanly back to source.",
            category: MigrationBoundary,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0099,
            code_text: "K0099",
            title: "rustc error remapped to Kobo source",
            summary: "Rust reported an error in generated code and Kobo mapped it back to the original source.",
            explain: "Kobo users should not need to inspect generated Rust for routine errors. K0099 is the bridge diagnostic when rustc remains the source of truth.",
            category: RustcRemap,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0100,
            code_text: "K0100",
            title: "syntax error recovered",
            summary: "Kobo recovered from invalid syntax and continued compiling the remaining trustworthy source regions.",
            explain: "Kobo keeps parsing after localized syntax errors so it can report other independent diagnostics. The poisoned region is skipped by later compiler phases to avoid cascades.",
            category: Parser,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0101,
            code_text: "K0101",
            title: "unclosed delimiter",
            summary: "A delimiter was opened but not closed before the parser reached a synchronization boundary.",
            explain: "Kobo recovered by treating the unterminated region as poisoned and resuming at the next safe item or statement boundary.",
            category: Parser,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0102,
            code_text: "K0102",
            title: "invalid item skipped",
            summary: "Kobo skipped an invalid item while preserving later parseable items.",
            explain: "The skipped item is not lowered to KIR. Later phases operate only on parseable source regions so follow-on diagnostics stay trustworthy.",
            category: Parser,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0103,
            code_text: "K0103",
            title: "parser recovery limit reached",
            summary: "Kobo stopped recovery after too many syntax errors to avoid misleading cascades.",
            explain: "Fix the first reported syntax errors and rerun Kobo. The parser intentionally stops after the recovery budget is exhausted.",
            category: Parser,
            status: Active,
            default_severity: Error,
            severity_policy: Always(Error),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0107,
            code_text: "K0107",
            title: "unmodeled external crate boundary",
            summary: "An external crate boundary is usable for normal Rust compatibility but blocks exact replay until a boundary policy is chosen.",
            explain: "Normal Rust crates remain allowed in Kobo, while replay and simulation need an explicit boundary policy such as model, record, outside, opaque, or debt before Kobo can claim deterministic evidence across that boundary.",
            category: MigrationBoundary,
            status: Active,
            default_severity: Warning,
            severity_policy: Always(Warning),
        },
        DiagnosticRegistryEntry {
            code: KErrorCode::K0108,
            code_text: "K0108",
            title: "replay obligation suppressed",
            summary: "A replay or boundary obligation was suppressed with a recorded reason.",
            explain: "Kobo allows reason-bearing suppression for future replay obligations, but records it as reviewable evidence instead of pretending the boundary was modeled.",
            category: MigrationBoundary,
            status: Active,
            default_severity: Warning,
            severity_policy: Always(Warning),
        },
    ]
}
