[package]
name    = "kobo-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
kobo-ir     = { path = "../kobo-ir" }
kobo-parser = { path = "../kobo-parser" }
serde      = { workspace = true }
serde_json = { workspace = true }
syn        = { workspace = true }
thiserror  = { workspace = true }
toml       = { workspace = true }
